site_name: kafka 使用手册
site_url: https://mapan1984.github.io/kafka-manual/
repo_url: https://github.com/mapan1984/kafka-manual/
site_description: kafka 使用手册
site_author: mapan

nav:
  - 1. 基础操作: '1-基础操作/index.md'
  - 2. 其他操作:
    - 1. 版本升级: '2-其他操作/kafka-upgrade.md'
    - 2. 转发服务: '2-其他操作/kafka-proxy.md'
  - 3. 常用配置: '3-常用配置/index.md'

theme:
  # name: readthedocs
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: deep orange
  language: 'zh'

plugins:
  - section-index
  - search:
      lang:
        - en
        - ja

extra_css: []


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
