site_name: kafka 使用手册
site_url: https://mapan1984.github.io/kafka-manual/
repo_url: https://github.com/mapan1984/kafka-manual/
site_description: kafka 使用手册
site_author: mapan

nav:
  - 1. 基础操作: '1-基础操作/index.md'
  - 2. 其他操作:
    - 1. 版本升级: '2-其他操作/kafka-upgrade.md'
    - 2. 转发服务: '2-其他操作/kafka-proxy.md'
    - 3. 手动迁移分区数据: '2-其他操作/kafka-move-partiton.md'
  - 3. 常用配置: '3-常用配置/index.md'
  - 4. 监控: '4-监控/index.md'

theme:
  # name: readthedocs
  name: material
  language: 'zh'
  # palette:
  #   scheme: slate
  #   primary: blue grey
  #   accent: deep orange
  palette: 
    - scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - section-index
  - search:
      lang:
        - en
        - ja

extra_css: []


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - tables
