upstream tcp9092 {
    server 10.0.0.1:9092;
}
upstream tcp9093 {
    server 10.0.0.2:9093;
}
upstream tcp9094 {
    server 10.0.0.3:9094;
}

server {
    listen 9092;
    proxy_connect_timeout 8s;
    proxy_timeout 24h;
    proxy_pass tcp9004;
}
server {
    listen 9093;
    proxy_connect_timeout 8s;
    proxy_timeout 24h;
    proxy_pass tcp9093;
}
server {
    listen 9094;
    proxy_connect_timeout 8s;
    proxy_timeout 24h;
    proxy_pass tcp9094;
}

